config/routes.rb
Rails.application.routes.draw do
  resources :tasks do 
    member do 
      put :change
      patch :complete
    end 
  end 
  
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  def completed?
  	!completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change, :complete]


  def change
    @task.update_attributes(state: params[:state])
    redirect_to tasks_path, notice: 'Task status was successfully changed.' 
  end

  def complete
		@task.update_attribute(:completed_at, Time.now)
    redirect_to root_url, notice: "Task completed"
  end
  
  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = Task.where(state: 'to_do')
    @doing = Task.where(state: 'doing')
    @done = Task.where(state: 'done')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
  <%= javascript_include_tag 'https://use.fontawesome.com/releases/v5.0.10/js/all.js' %>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :task_content %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<!--
      <tr>
        <td><%= task.content %></td>
        <td><%= task.state %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        

        <% if task.state == 'doing' %>

          <td><%= link_to 'Mark as to_do', change_task_path(task, state:"to_do"), method: :put %></td>
          <td><%= link_to 'Mark as Done', change_task_path(task, state:"done"), method: :put %></td>
        
        <% else %>

          <td><%= link_to 'Mark as Doing', change_task_path(task, state:"doing"), method: :put %></td>

        <% end %>

      </tr>
-->

      <div class = "panel panel-info">
        <div class = "panel-heading">
          <%= link_to edit_task_path(task) do %>
            Created: <%= time_ago_in_words(task.created_at) %> ago
          <% end %>
        </div>
        
        <div class = "panel-body">
          <div class="row">        
              <% if task.state == 'done'%>  
                <% if task.completed? %>
                  <div class="col-md-4">
                    <%= link_to complete_task_path(task), method: :patch do %> 
                      <i style="opacity: 0.4" class="fa fa-check" ></i>
                    <% end %> 
                  </div> 
                  <div>
                    <p style="opacity: 0.4" ><strike><%= task.content %> </strike></p>
                  </div>
                  
                  <div class="col-md-4">
                    <%= link_to task_path(task), method: :delete, data: { confirm: "voce tem certeza?"} do %>
                      <i class="fa fa-trash"></i>	
                    <% end %>  
                  </div>
                <% else %>
                  <div class="col-md-4">
                    <%= link_to complete_task_path(task), method: :patch do %> 
                      <i class="fa fa-check" ></i>
                    <% end %> 
                  </div> 
                  <div>
                    <p><%= task.content %></p>
                  </div>
                  
                  <div class="col-md-4">
                    <%= link_to task_path(task), method: :delete, data: { confirm: "voce tem certeza?"} do %>
                      <i class="fa fa-trash"></i>	
                    <% end %>  
                  </div>
                <% end %>
              <% else %>
                <div class = "panel-body">
                  <%= task.content %>
                </div>
              <% end %>
          </div> 
        </div>

        <div class = "panel-footer">
          <div class = "btn-group btn-group-justified">

            <% if task.state == 'doing' %>

              <%= link_to  change_task_path(task, state:"to_do"), method: :put, class: 'btn btn-info btn-block' do %>
                <i class="fa fa-arrow-left"></i>
              <% end %>

              <%= link_to  change_task_path(task, state:"done"), method: :put, class: 'btn btn-info btn-block' do %>
                <i class="fa fa-arrow-right"></i>
              <% end %>

<!--
              <%= link_to '<i class="fa fa-arrow-left"></i>'.html_safe, change_task_path(task, state:"to_do"), method: :put, class: 'btn btn-info btn-block' %>
              <%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, change_task_path(task, state:"done"), method: :put, class: 'btn btn-info btn-block' %>
-->            
            <% elsif task.state == 'done' %>
              
             <%= link_to '<i class="fa fa-arrow-left"></i>'.html_safe, change_task_path(task, state:"doing"), method: :put, class: 'btn btn-info btn-block' %>

            <% else %>

              <%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, change_task_path(task, state:"doing"), method: :put, class: 'btn btn-info btn-block' %>
            
            <% end %>

          </div>
        </div>
      </div>   

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', root_url %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'New Task', new_task_path %>


<div class="row">
  <div class="col-md-4">
    <h1>Aberto</h1>
      <%= render @to_do %>
  </div>

  <div class="col-md-4">
    <h1>Em Analise</h1>
      <%= render @doing %>
  </div>

  <div class="col-md-4">
    <h1>Concluído</h1>
      <%= render @done %>      
  </div>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>